version: '3'

services:
  web:
    build: .
      # context: .
      # dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    # python manage.py makemigrations && python manage.py migrate && python manage.py runserver
    # python manage.py makemigrations && python manage.py migrate &&
    volumes:
      - .:/socialnetworking
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      DB_HOST: db
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:


